Improve run for Android phone

diff --git a/run b/run
--- a/run
+++ b/run
@@ -8,11 +8,17 @@ uid=$(id -u)
 
 MODS="colors watchr path fs vm websocket process crypto fibers yauzl http path os cheerio"
 
+which bc >/dev/null || apt-get -y install bc
 nodever=$(nodejs --version 2>/dev/null | sed -e 's/v/((((/g' -e 's/\./)*100)+/g' | bc)
+[ "$nodever" = "" ] && nodever=0
 if [ "$nodever" -le "1025" ]; then
+	which curl >/dev/null || apt-get -y install curl
 	echo "Installing new nodejs (nodever=$nodever)"
 	curl -sL https://deb.nodesource.com/setup_4.x | bash -
-	apt-get install -y nodejs
+	apt-get install -y nodejs || {
+		echo "Install failed.  Exiting."
+		exit
+	}
 fi
 
 echo "Checking for modules to install..."
@@ -36,4 +42,3 @@ while [ true ]; do
     } 
     sleep 1
 done
-v0.10.25
